-- Add migration script here

CREATE TABLE regions
(
    id      UUID PRIMARY KEY,
    slug    VARCHAR NOT NULL UNIQUE,
    options JSON    NOT NULL
);

INSERT INTO regions(id, slug, options)
VALUES ('8c4144a5-4340-4169-b1cb-e8f963022a0c'::uuid,
        'us-west',
        '{
          "bridge": {
            "basePath": "http://localhost:8081"
          },
          "kube": {
            "apiVersion": "v1",
            "clusters": [
              {
                "cluster": {
                  "certificate-authority-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJek1UQXlOREF5TlRZeE0xb1hEVE16TVRBeU1qQXlOVFl4TTFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGxiCldrU1cvandDZ29tUE5rSXd1OUZvT20rVkRsaGV4RFFyb0lZeTZhUm1mZVA2STcyWEV2c3o4a0VIWlBWaXJMMXQKZHZxWWlSMGt3QmRjRHZCRkh5U29GV0NKVFBwRVd5RUFWQ3IrZVN5cm1HcjFtZU5TNUVxMnZDVXRIZ2Rod1orRgo1S2hqaGlsTWFEOFdoL1lUdVFJSU1lQk9Ld1NSUGlDMWNjYkhyTGNxUllOZVlHZDhlRlJsQXNNWXRRZFYrUmdaCjQ1bTFkTWVIaFpXTWM3aDZsWW1VZ1VLREF0dFVCTUVNZWhoZ2ZMOUIrWm11Z2VleXNSLzlkVWxseXdSWGdVYkcKWEZmNW5uY3ZHVkVhU3BiUGxtQ2JCNmNpSGsyclpkZ0JzTDNvY2VvZEhFWWxid1dHbWNYUURMbDhtcU42N0hiaApjdnl2WXU1Q1JWblJPRWpTVXpFQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSWlZsanpTYVFSNHNHeE5nbmpWVVU0dkJoSWlEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFmQlVnbCttNApTK0RCV09sR053MVNSanZTbitTVjN2ZVkyeDA3OE53V295R1RJR2xzaFBHZEMzRVg5dDVOVmhFZlFMalZ6TjBsCks4NFhJMVVRSlBGTTR6U0FFeDFkSHZlTWkxZXdHRWQ4b25QN215dFh5dHpBNXA0REwvQkt2RmZvNlpiOTk0Z0QKSVBTSWlWSXhWVjgzeDBxL0tJb20yUUdLeGdKSDJkQ2RUNDBLeC8yNnFSVVI4YWRXdGFLOXFOUGhwN3lUMU5aVQp4blM4YlNPQ0gvZ3QxQVd1UkZ3VEdsOVl1WWk5bzhiWktqMDRQV05jZEtjbDZ2ZlJaa0tEd1FQODZkYzBvYkxmCmNkWGEreTFPbTNqY2xhMThKajkvRVFXZ1g3ZCtLZDcwU0ZlajFWTmxDSmVoNytNUzAyakpxSXZzdHZWNE81ZG0KNnpicHhrcTQzaVpxMkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==",
                  "extensions": [
                    {
                      "extension": {
                        "last-update": "Thu, 26 Oct 2023 15:06:35 -03",
                        "provider": "minikube.sigs.k8s.io",
                        "version": "v1.31.2"
                      },
                      "name": "cluster_info"
                    }
                  ],
                  "server": "https://192.168.49.2:8443"
                },
                "name": "minikube"
              }
            ],
            "contexts": [
              {
                "context": {
                  "cluster": "minikube",
                  "extensions": [
                    {
                      "extension": {
                        "last-update": "Thu, 26 Oct 2023 15:06:35 -03",
                        "provider": "minikube.sigs.k8s.io",
                        "version": "v1.31.2"
                      },
                      "name": "context_info"
                    }
                  ],
                  "namespace": "default",
                  "user": "minikube"
                },
                "name": "minikube"
              }
            ],
            "current-context": "minikube",
            "kind": "Config",
            "preferences": {},
            "users": [
              {
                "name": "minikube",
                "user": {
                  "clients-certificate-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJek1UQXlOREF5TlRZeE0xb1hEVEkyTVRBeU5EQXlOVFl4TTFvd01URVhNQlVHQTFVRQpDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGakFVQmdOVkJBTVREVzFwYm1scmRXSmxMWFZ6WlhJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDaVN0dzNYanZjcXNrcWlvQ1NucWg3ZGhZTjZDbVEKY3JrV0JkT2JWeEpNU0FlZnZ0WHZSb3puNGU5Q1ZLNjFQcnhtQ09xZkpTakpmSnAwWmNvcnVQY3FEWjZFN2ZlTAptMjFRRXBDcHQ2Sm5JazliUHBmSzB1Z1EzbkZZaUgxZnFQc0FxRjVJRjMrUjYvaXl5QVVkUWx6KzkxYk9MREtqCmhHMGdpd1ViL0h0TjNoZ2RrTTVNOWxtRlc5NGFkdHYrb2dmQVBDd1RIaTRWTW9WNmkyRXUwMjh5Y21wSS91cFoKNitEMGpycWJUYXkwQUdxQ2lUU3BsRTNwbDRCTTVyZmp2czdIblBNL01FYnJaekxMdkYwb1U5L2dLNlc1U1N6cQpkRXNFTXIyTmJXL25ERTlvTWZKZUNRMFlPdXRieCtUMStQNG4zaDVYWGlsMTc4MUJvc092emlockFnTUJBQUdqCllEQmVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSWlZsanpTYVFSNHNHeE5nbmpWVVU0dkJoSQppREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQWZjWkIrNFNDeVg1a3N3RW9Hb0ZoN0RjblJ0enJoRGlsSk02CjlpNjVNanJmSFByWjhXOU5HaEFRUjRTZW9ZaG5TYVhrK2lEaDdiVU0wVXhvM2oreFRqQnRtL3FjV0pDQ09VNHYKUFFYaklSNkVCM0ZWZk9PbXNLc2xoS1IwdDZJWjBFRld2RE1UcUNNWnZDdklRMTNoTW9QNjBiMXhmR0o1NGx3WgpvbDB4MVVoNlVYTW1LT1hkcStCWnRGeE1veEVhTTdFamRpMVBmNHhMSTZBZ1J6N0lTbEdlYmFOMzBTeEpEL1BlCjlOVFJJVE9SZnF1cGZRNVZBOXp6ZXRnMnNXNFdhZjBzT1VVRlF6WHJpTWFaY0p5Qzl4U2xRUk0yOVJJWHJvUXUKK0JrM2gwb1JtTW5zOG1ZdGZhWFVwV1BuTEJLT205ajBWYnBVYUdjdXpwelRtVXNJcXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==",
                  "clients-key-data": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBb2tyY04xNDczS3JKS29xQWtwNm9lM1lXRGVncGtISzVGZ1hUbTFjU1RFZ0huNzdWCjcwYU01K0h2UWxTdXRUNjhaZ2pxbnlVb3lYeWFkR1hLSzdqM0tnMmVoTzMzaTV0dFVCS1FxYmVpWnlKUFd6NlgKeXRMb0VONXhXSWg5WDZqN0FLaGVTQmQva2V2NHNzZ0ZIVUpjL3ZkV3ppd3lvNFJ0SUlzRkcveDdUZDRZSFpETwpUUFpaaFZ2ZUduYmIvcUlId0R3c0V4NHVGVEtGZW90aEx0TnZNbkpxU1A3cVdldmc5STY2bTAyc3RBQnFnb2swCnFaUk42WmVBVE9hMzQ3N094NXp6UHpCRzYyY3l5N3hkS0ZQZjRDdWx1VWtzNm5STEJESzlqVzF2NXd4UGFESHkKWGdrTkdEcnJXOGZrOWZqK0o5NGVWMTRwZGUvTlFhTERyODRvYXdJREFRQUJBb0lCQUVCK2QxMFplYmlMdGozTgpwS0tmb2x6TjVKM0tNUnBTUFBOZmhXUXFDZjkrY0drdk1WMVJNQlhHVjRxSWxKVTZSU3hYUnNYUHdwR3Zqc0hLCjRialdYSUs5dnMwY3RFOHFpUnBWQm1BcnRjSStoRUxDY1JnTkVHUUR3ZzlvemtvQm9SMzF5dUhqVkxMc2ozeWMKdUV1VVg5aUMrbUFjZUZNN0FSTDVyQ0lmQi9FOU8wcHpCZXRCbnZ0aVUrR21aNWk1bXRIMnNSck51UlBSdXNJMwpMWkljMW15VlBoZU1wVmJnZHk0QWZQQ3dKMko2ZWhXOUo5aWVVUjNRUUp1VncycjJuNjdJSjNHaURyNUxvT1NjCkd0VXQrVTNXS2draVo2ZlhUU3J4OXNFTGRWQUV6MStvUGFXM1paMkxvcSsvREVnek9HWFo1dStmNkFzZyt0cEQKcXJpRlpnRUNnWUVBMGxuV1hoRGtJWVlGcFVuYlVGVCtCN3FENVRUQ1NhUlgwZDRqcUVFZmx0ZXdvRXQwVkE3Vgp6WjhnYWlwMlN4cWlMSXozRTdEaWlRZWlOSDZhNFg1cmxBb3g0ODZjV0l3ZXl5cnFzM0YwN2xJSUhMbFFHK2grCjVuQU1QSG5VRjZvYW1LMUk1blc2VklZMkU4R3FQUzV4akF0cDZCTXFMY1RCZm5wS0hnZ2FaNnNDZ1lFQXhZTWIKSGpIYVhYVXBBMnZRR2dDdDFZWVVGL3liS0FOeG5rMFU0WndzSnpadUxDanI3ZzVTY3FmaVdpNGJtTzdkM091TgpXeER1c2U0WUVaM2ZWRk1QdTg2dU1aYndBcWdudlV6SlZUOFpudjAzdE9MQldFNytNTEl5clJWT3FBOFVGWEZaCm1mSEYzSDl5MEFVTFFSYUdKSEtKdGhNUkhINHMzMi8wN1VCZmdrRUNnWUFxZEQxQ3NQQUtJQTJGcFpsZzVqWjcKQXRiWjdNTUZyK2lWajlyc2UzQlB0bXFNZjQ0VDVRYWJ3SEQvWEdDUm1lZC9URmdWbms2cVQyTWFheThCTWMydQpqRHd6ZVNDdThtRElxbm5DQzdVSTRIK0lwSklaZjl3VTBDcDREaktUTUI2OEQ4VTExaTdzSGtaTnlIbCtiYUEzCkhwcWFYenZWRHUvcWdlM3hqN3NjandLQmdRQ255bUF3UDVQTmoybC9NWWtCZmhBdmRBNy83YVgxMFM4bGwwQWwKQmFKdzBZbTQxQzdSOXJMT0dwZHRtdnZ3NlFQcjJPUW1OL1UvalJBL2J3bTV2aktBanUxbXpWNHFNNlpHNThPbQpPc3ZPU0RtWjNvVDRPMnN2L1VLVnphTWJuR3VvWjdvQjBPWVJFdWg3bGIxZzF2eXdXK2xubHowVElwR0dZN3NFCkRvclV3UUtCZ1FERWthSmRFcDQydkoza1JzUzlkRjNreUlKQ1AwdUwvOVZkN1Q0aEcwWWJHQm4rOTlYcXUrd2gKcTJOdVBqRXlNZlA1UmtuM0FVTTRzM3hZQlJtQ2V0MEFScG9aWWd0U2J6STk4VGMvQVNGeEI0UlMxaVFPbjhoTgp5UWlxUGsxREUyb3lId2VYZGdhUk81VlU0UXpMcHhFQlJLSG51eEZxa3ZZNG45SkduOHdqL1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
                }
              }
            ]
          }
        }'
       )